// Generated by tauri-specta from src-tauri/src/commands. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listLibraryFolders: () => typedError<LibraryFolder[], IpcError>(__TAURI_INVOKE("list_library_folders")),
	/**  Adds a folder chosen in the native dialog and lets the webview load its files. */
	addLibraryFolder: (path: string) => typedError<LibraryFolder, IpcError>(__TAURI_INVOKE("add_library_folder", { path })),
	/**  Removes a library folder with its videos and thumbnails. Returns how many videos were removed. */
	removeLibraryFolder: (path: string) => typedError<number, IpcError>(__TAURI_INVOKE("remove_library_folder", { path })),
	setLibraryFolderIcon: (path: string, icon: string | null) => typedError<null, IpcError>(__TAURI_INVOKE("set_library_folder_icon", { path, icon })),
	/**  Folder icons chosen most recently, newest first, offered first by the icon picker. */
	recentFolderIcons: () => typedError<string[], IpcError>(__TAURI_INVOKE("recent_folder_icons")),
	/**  Sets how a folder lists its videos; `None` makes it inherit from its parent again. */
	setFolderViewMode: (path: string, mode: 
/**  Only the folder's own videos, mirroring the disk. The playlist is the folder itself. */
"folders" | 
/**  Every video in the tree, grouped by subfolder. The playlist spans the folder where the mode was set. */
"continuous" | null) => typedError<null, IpcError>(__TAURI_INVOKE("set_folder_view_mode", { path, mode })),
	browseFolder: (path: string) => typedError<FolderContents, IpcError>(__TAURI_INVOKE("browse_folder", { path })),
	getFolderSummary: (path: string) => typedError<FolderSummary, IpcError>(__TAURI_INVOKE("get_folder_summary", { path })),
	/**  The ordered list of videos that plays around `video_path` (its folder, or the continuous tree). */
	listPlaylist: (videoPath: string) => typedError<VideoEntry[], IpcError>(__TAURI_INVOKE("list_playlist", { videoPath })),
	/**  Home page sections, each limited to `limit` videos. */
	getHome: (limit: number) => typedError<HomeData, IpcError>(__TAURI_INVOKE("get_home", { limit })),
	getVideo: (path: string) => typedError<{
	id: number,
	filePath: string,
	title: string,
	description: string,
	durationSeconds: number,
	thumbnailPath: string | null,
	isWatched: boolean,
	watchProgressSeconds: number,
	lastWatchedAt: string | null,
	createdAt: string | null,
	updatedAt: string | null,
} | null, IpcError>(__TAURI_INVOKE("get_video", { path })),
	updateVideoDetails: (id: number, title: string, description: string) => typedError<Video, IpcError>(__TAURI_INVOKE("update_video_details", { id, title, description })),
	setWatched: (id: number, watched: boolean) => typedError<Video, IpcError>(__TAURI_INVOKE("set_watched", { id, watched })),
	/**  Saves the playback position; `finished` is set when playback reached the end of the video. */
	saveProgress: (id: number, positionSeconds: number | null, finished: boolean) => typedError<Video, IpcError>(__TAURI_INVOKE("save_progress", { id, positionSeconds, finished })),
	/**  Marks every video inside a folder as watched or unwatched. Returns how many changed. */
	setFolderWatched: (path: string, watched: boolean) => typedError<number, IpcError>(__TAURI_INVOKE("set_folder_watched", { path, watched })),
	/**  Clears the watch status of every video (tags are kept). Returns how many changed. */
	resetAllWatchStatus: () => typedError<number, IpcError>(__TAURI_INVOKE("reset_all_watch_status")),
	/**
	 *  A page of the watch history (one entry per video per day), newest first. Pass the previous page's
	 *  `nextCursor` to get older entries.
	 */
	listWatchHistory: (cursor: {
	watchedAt: string,
	videoId: number,
} | null, limit: number) => typedError<HistoryPage, IpcError>(__TAURI_INVOKE("list_watch_history", { cursor, limit })),
	/**
	 *  Watched time per local day over the last `days` days (today included), oldest first; days without history are
	 *  left out.
	 */
	getWatchTotals: (days: number) => typedError<DailyWatchTotal[], IpcError>(__TAURI_INVOKE("get_watch_totals", { days })),
	listTags: () => typedError<TagWithUsage[], IpcError>(__TAURI_INVOKE("list_tags")),
	/**  Creates an unused tag (normalized). Fails with `invalidInput` when the name is empty or taken. */
	createTag: (name: string) => typedError<Tag, IpcError>(__TAURI_INVOKE("create_tag", { name })),
	getVideoTags: (videoId: number) => typedError<Tag[], IpcError>(__TAURI_INVOKE("get_video_tags", { videoId })),
	/**  Adds a tag (normalized, created on demand) and returns the video's tags. */
	addTagToVideo: (videoId: number, name: string) => typedError<Tag[], IpcError>(__TAURI_INVOKE("add_tag_to_video", { videoId, name })),
	removeTagFromVideo: (videoId: number, tagId: number) => typedError<Tag[], IpcError>(__TAURI_INVOKE("remove_tag_from_video", { videoId, tagId })),
	/**  Tags every video inside a folder. Returns how many videos received the tag. */
	addTagToFolder: (path: string, name: string) => typedError<number, IpcError>(__TAURI_INVOKE("add_tag_to_folder", { path, name })),
	/**  Removes every tag from the videos inside a folder. Returns how many assignments were removed. */
	removeAllTagsFromFolder: (path: string) => typedError<number, IpcError>(__TAURI_INVOKE("remove_all_tags_from_folder", { path })),
	deleteTag: (tagId: number) => typedError<null, IpcError>(__TAURI_INVOKE("delete_tag", { tagId })),
	removeTagFromAllVideos: (tagId: number) => typedError<number, IpcError>(__TAURI_INVOKE("remove_tag_from_all_videos", { tagId })),
	deleteAllTags: () => typedError<number, IpcError>(__TAURI_INVOKE("delete_all_tags")),
	deleteUnusedTags: () => typedError<number, IpcError>(__TAURI_INVOKE("delete_unused_tags")),
	/**  Searches the library by title, description and tags. */
	searchLibrary: (query: string, limit: number) => typedError<Video[], IpcError>(__TAURI_INVOKE("search_library", { query, limit })),
	/**
	 *  Searches file names below a folder on disk, streaming progress. A newer search cancels this one, which then
	 *  fails with the `cancelled` error kind.
	 */
	searchFolder: (path: string, query: string, onProgress: Channel<SearchProgress>) => typedError<VideoEntry[], IpcError>(__TAURI_INVOKE("search_folder", { path, query, onProgress })),
	mediaToolsStatus: () => __TAURI_INVOKE<MediaToolsStatus>("media_tools_status"),
	/**
	 *  Extracts metadata and thumbnails for the new videos below a folder, streaming progress. Jobs run one at a time;
	 *  a second request waits for the first.
	 */
	processFolder: (path: string, onEvent: Channel<ProcessingEvent>) => typedError<ProcessingSummary, IpcError>(__TAURI_INVOKE("process_folder", { path, onEvent })),
	/**  Makes the frame at `position_seconds` the video's thumbnail, or restores the automatic one when `null`. */
	setVideoThumbnail: (id: number, positionSeconds: number | null) => typedError<Video, IpcError>(__TAURI_INVOKE("set_video_thumbnail", { id, positionSeconds })),
	/**  The external subtitle next to a video, if any. */
	findSubtitle: (videoPath: string) => typedError<{
	format: SubtitleFormat,
	content: string,
} | null, IpcError>(__TAURI_INVOKE("find_subtitle", { videoPath })),
	/**  The audio and subtitle streams inside a library video. */
	listMediaTracks: (path: string) => typedError<MediaTracks, IpcError>(__TAURI_INVOKE("list_media_tracks", { path })),
	/**
	 *  A text subtitle stream of a library video (`index` among its subtitle streams), converted to WebVTT. Reads the
	 *  whole file, so it can take a few seconds on large videos.
	 */
	extractSubtitle: (path: string, index: number) => typedError<SubtitleFile, IpcError>(__TAURI_INVOKE("extract_subtitle", { path, index })),
	getSettings: () => typedError<AppSettings, IpcError>(__TAURI_INVOKE("get_settings")),
	updateSettings: (settings: AppSettings) => typedError<AppSettings, IpcError>(__TAURI_INVOKE("update_settings", { settings })),
	/**  Volume, speed, subtitles and layout of the player, as it was last left. */
	getPlayerPreferences: () => typedError<PlayerPreferences, IpcError>(__TAURI_INVOKE("get_player_preferences")),
	updatePlayerPreferences: (preferences: PlayerPreferences) => typedError<PlayerPreferences, IpcError>(__TAURI_INVOKE("update_player_preferences", { preferences })),
	/**  The keys of every configurable action, with defaults filling anything not customized. */
	getKeyboardShortcuts: () => typedError<KeyboardShortcuts, IpcError>(__TAURI_INVOKE("get_keyboard_shortcuts")),
	/**  Stores the keyboard shortcuts; rejects malformed, reserved or repeated keys and more than two keys per action. */
	updateKeyboardShortcuts: (shortcuts: KeyboardShortcuts) => typedError<KeyboardShortcuts, IpcError>(__TAURI_INVOKE("update_keyboard_shortcuts", { shortcuts })),
	getLibraryStats: () => typedError<LibraryStats, IpcError>(__TAURI_INVOKE("get_library_stats")),
	/**  Writes the whole library to a JSON file chosen in the native save dialog. */
	exportLibrary: (path: string) => typedError<null, IpcError>(__TAURI_INVOKE("export_library", { path })),
	/**  Replaces the library with a JSON export (current or legacy format). All or nothing. */
	importLibrary: (path: string) => typedError<ImportSummary, IpcError>(__TAURI_INVOKE("import_library", { path })),
	getDatabaseInfo: () => typedError<DatabaseInfo, IpcError>(__TAURI_INVOKE("get_database_info")),
	listOrphanedVideos: () => typedError<Video[], IpcError>(__TAURI_INVOKE("list_orphaned_videos")),
	cleanOrphanedVideos: () => typedError<number, IpcError>(__TAURI_INVOKE("clean_orphaned_videos")),
	/**  Opens a library file with the system's default application. */
	openExternally: (path: string) => typedError<null, IpcError>(__TAURI_INVOKE("open_externally", { path })),
	/**  Shows a library file selected in the system file manager. */
	revealInFileManager: (path: string) => typedError<null, IpcError>(__TAURI_INVOKE("reveal_in_file_manager", { path })),
};

/* Constants */
export const DEFAULT_KEYBOARD_SHORTCUTS = {"fullscreen":["F"],"historyBack":["Alt+ArrowLeft"],"historyForward":["Alt+ArrowRight"],"mute":["M"],"playPause":["Space","K"],"seekBack10":["J"],"seekBack5":["ArrowLeft"],"seekForward10":["L"],"seekForward5":["ArrowRight"],"speedDown":["["],"speedReset":["Backspace"],"speedUp":["]"],"subtitles":["C"],"theater":["T"],"volumeDown":["ArrowDown"],"volumeUp":["ArrowUp"]} as const;

export const DEFAULT_PLAYER_PREFERENCES = {"muted":false,"speed":1.0,"subtitlesEnabled":true,"theater":false,"upNextWidth":null,"volume":1.0} as const;

export const DEFAULT_WATCHED_THRESHOLD = 0.9 as const;

export const MAX_KEYS_PER_SHORTCUT = 2 as const;

export const MAX_PLAYBACK_SPEED = 2.0 as const;

export const MAX_UP_NEXT_WIDTH = 800 as const;

export const MAX_WATCHED_THRESHOLD = 1.0 as const;

export const MIN_PLAYBACK_SPEED = 0.25 as const;

export const MIN_UP_NEXT_WIDTH = 240 as const;

export const MIN_WATCHED_THRESHOLD = 0.5 as const;

export const PLAYBACK_SPEED_STEP = 0.25 as const;

export const RESERVED_SHORTCUT_KEYS = ["Escape","?","Tab","Shift+Tab","Enter"] as const;

export const WATCHED_THRESHOLD_STEP = 0.05 as const;

/* Types */
/**  User-adjustable settings. */
export type AppSettings = {
	watchedThreshold: number,
};

export type AudioTrack = {
	/**  Position among the file's audio streams (ffmpeg's `0:a:<index>`). */
	index: number,
	/**  ISO 639 code from the file, when it has one other than "undetermined". */
	language: string | null,
	title: string | null,
	codec: string,
	channels: number | null,
	isDefault: boolean,
};

/**  How much was watched on one local day: the videos that became watched and their total length. */
export type DailyWatchTotal = {
	/**  Local date, `YYYY-MM-DD`. */
	day: string,
	videos: number,
	seconds: number,
};

export type DatabaseInfo = {
	path: string,
	sizeBytes: number,
	schemaVersion: number,
};

export type ErrorKind = "database" | "io" | "notFound" | "invalidInput" | "mediaToolMissing" | "mediaProcessFailed" | "timeout" | "importFormat" | "cancelled" | "internal";

export type FileEntry = {
	name: string,
	path: string,
};

/**
 *  Everything the folder screen shows. In `folders` mode there is at most one group (the folder's own videos);
 *  in `continuous` mode there is one group per folder of the tree that has videos, in natural path order.
 */
export type FolderContents = {
	path: string,
	viewMode: ResolvedViewMode,
	subfolders: SubfolderEntry[],
	groups: VideoGroup[],
	otherFiles: FileEntry[],
};

export type FolderPreview = {
	folder: LibraryFolder,
	videos: Video[],
};

export type FolderStats = {
	totalVideos: number,
	watchedVideos: number,
};

/**  Data for the folder context menu. */
export type FolderSummary = {
	totalVideos: number,
	watchedVideos: number,
	taggedVideos: number,
};

/**  How a folder lists its videos. Set per folder and inherited by its descendants until overridden. */
export type FolderViewMode = 
/**  Only the folder's own videos, mirroring the disk. The playlist is the folder itself. */
"folders" | 
/**  Every video in the tree, grouped by subfolder. The playlist spans the folder where the mode was set. */
"continuous";

/**
 *  Where a page of the watch history ends; pass it back to get the next (older) page. `watched_at` is the stored
 *  timestamp, so treat the cursor as opaque.
 */
export type HistoryCursor = {
	watchedAt: string,
	videoId: number,
};

/**  A video that became watched on a given day. */
export type HistoryEntry = {
	video: Video,
	/**  Local date, `YYYY-MM-DD`. */
	day: string,
	/**  When it first became watched that day, ISO 8601 in UTC. */
	watchedAt: string,
};

export type HistoryPage = {
	/**  Newest first. */
	entries: HistoryEntry[],
	nextCursor: HistoryCursor | null,
};

export type HomeData = {
	continueWatching: Video[],
	recentlyWatched: Video[],
	suggestions: Video[],
	folderPreviews: FolderPreview[],
};

export type ImportSummary = {
	folders: number,
	videos: number,
	tags: number,
};

/**  Wire format of [`AppError`]: a stable `kind` for the UI to branch on and a human-readable `message`. */
export type IpcError = {
	kind: ErrorKind,
	message: string,
};

/**  The keys of every configurable action. Empty lists are allowed: the action simply has no key. */
export type KeyboardShortcuts = {
	playPause: string[],
	seekBack10: string[],
	seekForward10: string[],
	seekBack5: string[],
	seekForward5: string[],
	volumeUp: string[],
	volumeDown: string[],
	mute: string[],
	speedDown: string[],
	speedUp: string[],
	speedReset: string[],
	fullscreen: string[],
	theater: string[],
	subtitles: string[],
	historyBack: string[],
	historyForward: string[],
};

export type LibraryFolder = {
	id: number,
	path: string,
	name: string,
	customIcon: string | null,
	createdAt: string | null,
};

export type LibraryStats = {
	totalVideos: number,
	watchedVideos: number,
	totalDurationSeconds: number,
	totalTags: number,
	totalFolders: number,
	orphanedVideos: number,
};

export type MediaToolsStatus = {
	ffmpeg: boolean,
	ffprobe: boolean,
};

/**  The audio and subtitle streams inside a video file, in file order. */
export type MediaTracks = {
	audio: AudioTrack[],
	subtitles: SubtitleTrack[],
};

/**
 *  How the built-in player was left: kept between sessions and used for every video. Fields missing from a stored
 *  value take their default (see `db::settings::Player`), so fields can be added later without a migration.
 */
export type PlayerPreferences = {
	/**  From 0 (silent) to 1 (full). */
	volume: number,
	muted: boolean,
	speed: number,
	subtitlesEnabled: boolean,
	theater: boolean,
	/**  Width of the "Up next" column in pixels, set by dragging its edge; `None` lets it follow the window. */
	upNextWidth: number | null,
};

/**  Progress of a background media processing job, streamed to the frontend through a channel. */
export type ProcessingEvent = { event: "started"; data: {
	folder: string,
	total: number,
} } | { event: "progress"; data: {
	done: number,
	total: number,
	currentFile: string,
} } | { event: "finished"; data: ProcessingSummary };

export type ProcessingSummary = {
	processed: number,
	skipped: number,
	failed: number,
};

/**  The effective view mode of a folder and the folder that defines it (`None` means the default applies). */
export type ResolvedViewMode = {
	mode: FolderViewMode,
	definedAt: string | null,
};

/**  Progress of a recursive folder search. */
export type SearchProgress = {
	scannedFiles: number,
	currentFolder: string,
};

export type SubfolderEntry = {
	name: string,
	path: string,
	stats: FolderStats,
};

export type SubtitleFile = {
	format: SubtitleFormat,
	content: string,
};

export type SubtitleFormat = "srt" | "vtt" | "sub" | "ass";

export type SubtitleTrack = {
	/**  Position among the file's subtitle streams (ffmpeg's `0:s:<index>`). */
	index: number,
	language: string | null,
	title: string | null,
	codec: string,
	isDefault: boolean,
	isForced: boolean,
	/**  Text subtitles can be extracted and shown; image ones (PGS, VobSub, DVB) cannot without OCR. */
	isText: boolean,
};

export type Tag = {
	id: number,
	name: string,
};

export type TagWithUsage = {
	id: number,
	name: string,
	videoCount: number,
};

/**  A processed video as stored in the library. */
export type Video = {
	id: number,
	filePath: string,
	title: string,
	description: string,
	durationSeconds: number,
	thumbnailPath: string | null,
	isWatched: boolean,
	watchProgressSeconds: number,
	lastWatchedAt: string | null,
	createdAt: string | null,
	updatedAt: string | null,
};

/**  A video file on disk, with its library record when it has already been processed. */
export type VideoEntry = {
	path: string,
	name: string,
	video: Video | null,
};

/**  Videos of one folder. `relative_path` is empty for the browsed folder itself. */
export type VideoGroup = {
	folderPath: string,
	relativePath: string,
	entries: VideoEntry[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

