// Generated by tauri-specta from src-tauri/src/commands. Do not edit.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listLibraryFolders: () => typedError<LibraryFolder[], IpcError>(__TAURI_INVOKE("list_library_folders")),
	/**  Adds a folder chosen in the native dialog and lets the webview load its files. */
	addLibraryFolder: (path: string) => typedError<LibraryFolder, IpcError>(__TAURI_INVOKE("add_library_folder", { path })),
	/**  Removes a library folder with its videos and thumbnails. Returns how many videos were removed. */
	removeLibraryFolder: (path: string) => typedError<number, IpcError>(__TAURI_INVOKE("remove_library_folder", { path })),
	setLibraryFolderIcon: (path: string, icon: string | null) => typedError<null, IpcError>(__TAURI_INVOKE("set_library_folder_icon", { path, icon })),
	/**  Sets how a folder lists its videos; `None` makes it inherit from its parent again. */
	setFolderViewMode: (path: string, mode: 
/**  Only the folder's own videos, mirroring the disk. The playlist is the folder itself. */
"folders" | 
/**  Every video in the tree, grouped by subfolder. The playlist spans the folder where the mode was set. */
"continuous" | null) => typedError<null, IpcError>(__TAURI_INVOKE("set_folder_view_mode", { path, mode })),
	browseFolder: (path: string) => typedError<FolderContents, IpcError>(__TAURI_INVOKE("browse_folder", { path })),
	getFolderSummary: (path: string) => typedError<FolderSummary, IpcError>(__TAURI_INVOKE("get_folder_summary", { path })),
	/**  The ordered list of videos that plays around `video_path` (its folder, or the continuous tree). */
	listPlaylist: (videoPath: string) => typedError<VideoEntry[], IpcError>(__TAURI_INVOKE("list_playlist", { videoPath })),
	/**  Home page sections, each limited to `limit` videos. */
	getHome: (limit: number) => typedError<HomeData, IpcError>(__TAURI_INVOKE("get_home", { limit })),
	getVideo: (path: string) => typedError<{
	id: number,
	filePath: string,
	title: string,
	description: string,
	durationSeconds: number,
	thumbnailPath: string | null,
	isWatched: boolean,
	watchProgressSeconds: number,
	lastWatchedAt: string | null,
	createdAt: string | null,
	updatedAt: string | null,
} | null, IpcError>(__TAURI_INVOKE("get_video", { path })),
	updateVideoDetails: (id: number, title: string, description: string) => typedError<Video, IpcError>(__TAURI_INVOKE("update_video_details", { id, title, description })),
	setWatched: (id: number, watched: boolean) => typedError<Video, IpcError>(__TAURI_INVOKE("set_watched", { id, watched })),
	/**  Saves the playback position; `finished` is set when playback reached the end of the video. */
	saveProgress: (id: number, positionSeconds: number | null, finished: boolean) => typedError<Video, IpcError>(__TAURI_INVOKE("save_progress", { id, positionSeconds, finished })),
	/**  Marks every video inside a folder as watched or unwatched. Returns how many changed. */
	setFolderWatched: (path: string, watched: boolean) => typedError<number, IpcError>(__TAURI_INVOKE("set_folder_watched", { path, watched })),
	/**  Clears the watch status of every video (tags are kept). Returns how many changed. */
	resetAllWatchStatus: () => typedError<number, IpcError>(__TAURI_INVOKE("reset_all_watch_status")),
	listTags: () => typedError<TagWithUsage[], IpcError>(__TAURI_INVOKE("list_tags")),
	getVideoTags: (videoId: number) => typedError<Tag[], IpcError>(__TAURI_INVOKE("get_video_tags", { videoId })),
	/**  Adds a tag (normalized, created on demand) and returns the video's tags. */
	addTagToVideo: (videoId: number, name: string) => typedError<Tag[], IpcError>(__TAURI_INVOKE("add_tag_to_video", { videoId, name })),
	removeTagFromVideo: (videoId: number, tagId: number) => typedError<Tag[], IpcError>(__TAURI_INVOKE("remove_tag_from_video", { videoId, tagId })),
	/**  Tags every video inside a folder. Returns how many videos received the tag. */
	addTagToFolder: (path: string, name: string) => typedError<number, IpcError>(__TAURI_INVOKE("add_tag_to_folder", { path, name })),
	/**  Removes every tag from the videos inside a folder. Returns how many assignments were removed. */
	removeAllTagsFromFolder: (path: string) => typedError<number, IpcError>(__TAURI_INVOKE("remove_all_tags_from_folder", { path })),
	deleteTag: (tagId: number) => typedError<null, IpcError>(__TAURI_INVOKE("delete_tag", { tagId })),
	removeTagFromAllVideos: (tagId: number) => typedError<number, IpcError>(__TAURI_INVOKE("remove_tag_from_all_videos", { tagId })),
	deleteAllTags: () => typedError<number, IpcError>(__TAURI_INVOKE("delete_all_tags")),
	deleteUnusedTags: () => typedError<number, IpcError>(__TAURI_INVOKE("delete_unused_tags")),
	/**  Searches the library by title, description and tags. */
	searchLibrary: (query: string, limit: number) => typedError<Video[], IpcError>(__TAURI_INVOKE("search_library", { query, limit })),
	/**
	 *  Searches file names below a folder on disk, streaming progress. A newer search cancels this one, which then
	 *  fails with the `cancelled` error kind.
	 */
	searchFolder: (path: string, query: string, onProgress: Channel<SearchProgress>) => typedError<VideoEntry[], IpcError>(__TAURI_INVOKE("search_folder", { path, query, onProgress })),
	mediaToolsStatus: () => __TAURI_INVOKE<MediaToolsStatus>("media_tools_status"),
	/**
	 *  Extracts metadata and thumbnails for the new videos below a folder, streaming progress. Jobs run one at a time;
	 *  a second request waits for the first.
	 */
	processFolder: (path: string, onEvent: Channel<ProcessingEvent>) => typedError<ProcessingSummary, IpcError>(__TAURI_INVOKE("process_folder", { path, onEvent })),
	/**  The external subtitle next to a video, if any. */
	findSubtitle: (videoPath: string) => typedError<{
	format: SubtitleFormat,
	content: string,
} | null, IpcError>(__TAURI_INVOKE("find_subtitle", { videoPath })),
	getSettings: () => typedError<AppSettings, IpcError>(__TAURI_INVOKE("get_settings")),
	updateSettings: (settings: AppSettings) => typedError<AppSettings, IpcError>(__TAURI_INVOKE("update_settings", { settings })),
	getLibraryStats: () => typedError<LibraryStats, IpcError>(__TAURI_INVOKE("get_library_stats")),
	/**  Writes the whole library to a JSON file chosen in the native save dialog. */
	exportLibrary: (path: string) => typedError<null, IpcError>(__TAURI_INVOKE("export_library", { path })),
	/**  Replaces the library with a JSON export (current or legacy format). All or nothing. */
	importLibrary: (path: string) => typedError<ImportSummary, IpcError>(__TAURI_INVOKE("import_library", { path })),
	getDatabaseInfo: () => typedError<DatabaseInfo, IpcError>(__TAURI_INVOKE("get_database_info")),
	listOrphanedVideos: () => typedError<Video[], IpcError>(__TAURI_INVOKE("list_orphaned_videos")),
	cleanOrphanedVideos: () => typedError<number, IpcError>(__TAURI_INVOKE("clean_orphaned_videos")),
	/**  Opens a library file with the system's default application. */
	openExternally: (path: string) => typedError<null, IpcError>(__TAURI_INVOKE("open_externally", { path })),
	/**  Shows a library file selected in the system file manager. */
	revealInFileManager: (path: string) => typedError<null, IpcError>(__TAURI_INVOKE("reveal_in_file_manager", { path })),
};

/* Constants */
export const DEFAULT_WATCHED_THRESHOLD = 0.9 as const;

export const MAX_WATCHED_THRESHOLD = 1.0 as const;

export const MIN_WATCHED_THRESHOLD = 0.5 as const;

export const WATCHED_THRESHOLD_STEP = 0.05 as const;

/* Types */
/**  User-adjustable settings. */
export type AppSettings = {
	watchedThreshold: number,
};

export type DatabaseInfo = {
	path: string,
	sizeBytes: number,
	schemaVersion: number,
	tables: TableCount[],
};

export type ErrorKind = "database" | "io" | "notFound" | "invalidInput" | "mediaToolMissing" | "mediaProcessFailed" | "timeout" | "importFormat" | "cancelled" | "internal";

export type FileEntry = {
	name: string,
	path: string,
};

/**
 *  Everything the folder screen shows. In `folders` mode there is at most one group (the folder's own videos);
 *  in `continuous` mode there is one group per folder of the tree that has videos, in natural path order.
 */
export type FolderContents = {
	path: string,
	viewMode: ResolvedViewMode,
	subfolders: SubfolderEntry[],
	groups: VideoGroup[],
	otherFiles: FileEntry[],
};

export type FolderPreview = {
	folder: LibraryFolder,
	videos: Video[],
};

export type FolderStats = {
	totalVideos: number,
	watchedVideos: number,
};

/**  Data for the folder context menu. */
export type FolderSummary = {
	totalVideos: number,
	watchedVideos: number,
	taggedVideos: number,
};

/**  How a folder lists its videos. Set per folder and inherited by its descendants until overridden. */
export type FolderViewMode = 
/**  Only the folder's own videos, mirroring the disk. The playlist is the folder itself. */
"folders" | 
/**  Every video in the tree, grouped by subfolder. The playlist spans the folder where the mode was set. */
"continuous";

export type HomeData = {
	continueWatching: Video[],
	recentlyWatched: Video[],
	suggestions: Video[],
	folderPreviews: FolderPreview[],
};

export type ImportSummary = {
	folders: number,
	videos: number,
	tags: number,
};

/**  Wire format of [`AppError`]: a stable `kind` for the UI to branch on and a human-readable `message`. */
export type IpcError = {
	kind: ErrorKind,
	message: string,
};

export type LibraryFolder = {
	id: number,
	path: string,
	name: string,
	customIcon: string | null,
	createdAt: string | null,
};

export type LibraryStats = {
	totalVideos: number,
	watchedVideos: number,
	totalDurationSeconds: number,
	totalTags: number,
	totalFolders: number,
	orphanedVideos: number,
};

export type MediaToolsStatus = {
	ffmpeg: boolean,
	ffprobe: boolean,
};

/**  Progress of a background media processing job, streamed to the frontend through a channel. */
export type ProcessingEvent = { event: "started"; data: {
	folder: string,
	total: number,
} } | { event: "progress"; data: {
	done: number,
	total: number,
	currentFile: string,
} } | { event: "finished"; data: ProcessingSummary };

export type ProcessingSummary = {
	processed: number,
	skipped: number,
	failed: number,
};

/**  The effective view mode of a folder and the folder that defines it (`None` means the default applies). */
export type ResolvedViewMode = {
	mode: FolderViewMode,
	definedAt: string | null,
};

/**  Progress of a recursive folder search. */
export type SearchProgress = {
	scannedFiles: number,
	currentFolder: string,
};

export type SubfolderEntry = {
	name: string,
	path: string,
	stats: FolderStats,
};

export type SubtitleFile = {
	format: SubtitleFormat,
	content: string,
};

export type SubtitleFormat = "srt" | "vtt" | "sub" | "ass";

export type TableCount = {
	name: string,
	rows: number,
};

export type Tag = {
	id: number,
	name: string,
};

export type TagWithUsage = {
	id: number,
	name: string,
	videoCount: number,
};

/**  A processed video as stored in the library. */
export type Video = {
	id: number,
	filePath: string,
	title: string,
	description: string,
	durationSeconds: number,
	thumbnailPath: string | null,
	isWatched: boolean,
	watchProgressSeconds: number,
	lastWatchedAt: string | null,
	createdAt: string | null,
	updatedAt: string | null,
};

/**  A video file on disk, with its library record when it has already been processed. */
export type VideoEntry = {
	path: string,
	name: string,
	video: Video | null,
};

/**  Videos of one folder. `relative_path` is empty for the browsed folder itself. */
export type VideoGroup = {
	folderPath: string,
	relativePath: string,
	entries: VideoEntry[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

