//! IPC commands: a thin layer that adapts services to Tauri. TypeScript bindings are generated from this list.

mod library;
mod media;
mod search;
mod settings;
mod system;
mod tags;
mod videos;

use tauri_specta::{Builder, collect_commands};

use crate::domain::models::PlayerPreferences;
use crate::domain::player::{
    MAX_PLAYBACK_SPEED, MAX_UP_NEXT_WIDTH, MIN_PLAYBACK_SPEED, MIN_UP_NEXT_WIDTH, PLAYBACK_SPEED_STEP,
};
use crate::domain::shortcuts::{KeyboardShortcuts, MAX_KEYS_PER_SHORTCUT, RESERVED_SHORTCUT_KEYS};
use crate::domain::watch::{
    DEFAULT_WATCHED_THRESHOLD, MAX_WATCHED_THRESHOLD, MIN_WATCHED_THRESHOLD, WATCHED_THRESHOLD_STEP,
};

pub fn builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            library::list_library_folders,
            library::add_library_folder,
            library::remove_library_folder,
            library::set_library_folder_icon,
            library::recent_folder_icons,
            library::set_folder_view_mode,
            library::browse_folder,
            library::get_folder_summary,
            library::list_playlist,
            library::get_home,
            videos::get_video,
            videos::update_video_details,
            videos::set_watched,
            videos::save_progress,
            videos::set_folder_watched,
            videos::reset_all_watch_status,
            videos::list_watch_history,
            videos::get_watch_totals,
            tags::list_tags,
            tags::create_tag,
            tags::get_video_tags,
            tags::add_tag_to_video,
            tags::remove_tag_from_video,
            tags::add_tag_to_folder,
            tags::remove_all_tags_from_folder,
            tags::delete_tag,
            tags::remove_tag_from_all_videos,
            tags::delete_all_tags,
            tags::delete_unused_tags,
            search::search_library,
            search::search_folder,
            media::media_tools_status,
            media::process_folder,
            media::set_video_thumbnail,
            media::find_subtitle,
            media::list_media_tracks,
            media::extract_subtitle,
            settings::get_settings,
            settings::update_settings,
            settings::get_player_preferences,
            settings::update_player_preferences,
            settings::get_keyboard_shortcuts,
            settings::update_keyboard_shortcuts,
            settings::get_library_stats,
            settings::export_library,
            settings::import_library,
            settings::get_database_info,
            settings::list_orphaned_videos,
            settings::clean_orphaned_videos,
            system::open_externally,
            system::reveal_in_file_manager,
        ])
        .constant("DEFAULT_WATCHED_THRESHOLD", DEFAULT_WATCHED_THRESHOLD)
        .constant("MIN_WATCHED_THRESHOLD", MIN_WATCHED_THRESHOLD)
        .constant("MAX_WATCHED_THRESHOLD", MAX_WATCHED_THRESHOLD)
        .constant("WATCHED_THRESHOLD_STEP", WATCHED_THRESHOLD_STEP)
        .constant("MIN_PLAYBACK_SPEED", MIN_PLAYBACK_SPEED)
        .constant("MAX_PLAYBACK_SPEED", MAX_PLAYBACK_SPEED)
        .constant("PLAYBACK_SPEED_STEP", PLAYBACK_SPEED_STEP)
        .constant("MIN_UP_NEXT_WIDTH", MIN_UP_NEXT_WIDTH)
        .constant("MAX_UP_NEXT_WIDTH", MAX_UP_NEXT_WIDTH)
        .constant("DEFAULT_PLAYER_PREFERENCES", PlayerPreferences::default())
        .constant("DEFAULT_KEYBOARD_SHORTCUTS", KeyboardShortcuts::default())
        .constant("RESERVED_SHORTCUT_KEYS", RESERVED_SHORTCUT_KEYS)
        .constant("MAX_KEYS_PER_SHORTCUT", MAX_KEYS_PER_SHORTCUT)
        // Every integer crossing IPC is a row id, a count or a byte size, all far below 2^53, so JavaScript numbers
        // represent them exactly.
        .dangerously_cast_bigints_to_number()
}

#[cfg(test)]
mod tests {
    use specta_typescript::Typescript;

    use super::*;

    /// Path of the generated bindings, relative to `src-tauri`.
    const BINDINGS_PATH: &str = "../src/shared/ipc/bindings.ts";

    /// Regenerates the TypeScript bindings. Runs with `cargo test`, so they never drift from the commands.
    #[test]
    fn export_typescript_bindings() {
        builder()
            .export(
                Typescript::default()
                    .header("// Generated by tauri-specta from src-tauri/src/commands. Do not edit.\n"),
                BINDINGS_PATH,
            )
            .unwrap();
    }
}
