//! Data shapes exchanged with the frontend. Their TypeScript twins are generated by tauri-specta.
//!
//! `f64` fields are exported as `number` (specta defaults to `number | null` because NaN serializes as null); the
//! backend only ever produces finite values for them.

use serde::{Deserialize, Serialize};
use specta::Type;
use specta_typescript::Number;

use super::folder_view::ResolvedViewMode;

mod history;
mod playback;
mod processing;

pub use history::*;
pub use playback::*;
pub use processing::*;

/// A processed video as stored in the library.
#[derive(Debug, Clone, PartialEq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct Video {
    pub id: i64,
    pub file_path: String,
    pub title: String,
    pub description: String,
    #[specta(type = Number)]
    pub duration_seconds: f64,
    pub thumbnail_path: Option<String>,
    pub is_watched: bool,
    #[specta(type = Number)]
    pub watch_progress_seconds: f64,
    pub last_watched_at: Option<String>,
    pub created_at: Option<String>,
    pub updated_at: Option<String>,
}

/// A video file on disk, with its library record when it has already been processed.
#[derive(Debug, Clone, PartialEq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct VideoEntry {
    pub path: String,
    pub name: String,
    pub video: Option<Video>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct LibraryFolder {
    pub id: i64,
    pub path: String,
    pub name: String,
    pub custom_icon: Option<String>,
    pub created_at: Option<String>,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct FolderStats {
    pub total_videos: i64,
    pub watched_videos: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct SubfolderEntry {
    pub name: String,
    pub path: String,
    pub stats: FolderStats,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct FileEntry {
    pub name: String,
    pub path: String,
}

/// Videos of one folder. `relative_path` is empty for the browsed folder itself.
#[derive(Debug, Clone, PartialEq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct VideoGroup {
    pub folder_path: String,
    pub relative_path: String,
    pub entries: Vec<VideoEntry>,
}

/// Everything the folder screen shows. In `folders` mode there is at most one group (the folder's own videos);
/// in `continuous` mode there is one group per folder of the tree that has videos, in natural path order.
#[derive(Debug, Clone, PartialEq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct FolderContents {
    pub path: String,
    pub view_mode: ResolvedViewMode,
    pub subfolders: Vec<SubfolderEntry>,
    pub groups: Vec<VideoGroup>,
    pub other_files: Vec<FileEntry>,
}

/// Data for the folder context menu.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct FolderSummary {
    pub total_videos: i64,
    pub watched_videos: i64,
    pub tagged_videos: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct FolderPreview {
    pub folder: LibraryFolder,
    pub videos: Vec<Video>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct HomeData {
    pub continue_watching: Vec<Video>,
    pub recently_watched: Vec<Video>,
    pub suggestions: Vec<Video>,
    pub folder_previews: Vec<FolderPreview>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct Tag {
    pub id: i64,
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct TagWithUsage {
    pub id: i64,
    pub name: String,
    pub video_count: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct LibraryStats {
    pub total_videos: i64,
    pub watched_videos: i64,
    #[specta(type = Number)]
    pub total_duration_seconds: f64,
    pub total_tags: i64,
    pub total_folders: i64,
    pub orphaned_videos: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct DatabaseInfo {
    pub path: String,
    pub size_bytes: i64,
    pub schema_version: i64,
}

/// How a library folder is kept in step with the disk.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub enum FolderWatch {
    /// Changes are followed as they happen.
    Watching,
    /// The folder cannot be watched (see `reason`), so it is compared every few minutes.
    Polling,
    /// Watching is turned off in Settings: compared at startup and on "Sync folder".
    Off,
    /// The folder cannot be reached (an unplugged drive, an offline share). Its videos are kept as they are.
    Unavailable,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct LibraryFolderStatus {
    pub path: String,
    pub watch: FolderWatch,
    /// Why the folder cannot be watched.
    pub reason: Option<String>,
}

/// User-adjustable settings.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct AppSettings {
    #[specta(type = Number)]
    pub watched_threshold: f64,
    /// Follow changes in the library folders as they happen.
    pub watch_folders: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct MediaToolsStatus {
    pub ffmpeg: bool,
    pub ffprobe: bool,
}

/// Progress of a recursive folder search.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct SearchProgress {
    pub scanned_files: i64,
    pub current_folder: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Type)]
#[serde(rename_all = "camelCase")]
pub struct ImportSummary {
    pub folders: i64,
    pub videos: i64,
    pub tags: i64,
}
